//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuMuon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietPhieuMuon()
        {
            this.PhieuPhats = new HashSet<PhieuPhat>();
        }
    
        public string MaPhieu { get; set; }
        public string MaBS { get; set; }
        public Nullable<System.DateTime> NgayTraThucTe { get; set; }
        public string TrangThaiTra { get; set; }
    
        public virtual BanSaoSach BanSaoSach { get; set; }
        public virtual PhieuMuon PhieuMuon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuPhat> PhieuPhats { get; set; }
    }
}
