//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyThuVienEntities : DbContext
    {
        public QuanLyThuVienEntities()
            : base("name=QuanLyThuVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BanSaoSach> BanSaoSaches { get; set; }
        public virtual DbSet<ChiTietPhieuMuon> ChiTietPhieuMuons { get; set; }
        public virtual DbSet<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual DbSet<ChiTietTacGia> ChiTietTacGias { get; set; }
        public virtual DbSet<DocGia> DocGias { get; set; }
        public virtual DbSet<LoaiSach> LoaiSaches { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NhaXuatBan> NhaXuatBans { get; set; }
        public virtual DbSet<PhieuMuon> PhieuMuons { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public virtual DbSet<PhieuPhat> PhieuPhats { get; set; }
        public virtual DbSet<Sach> Saches { get; set; }
        public virtual DbSet<TacGia> TacGias { get; set; }
        public virtual DbSet<v_ThongKeSach> v_ThongKeSach { get; set; }
    
        public virtual int sp_DanhSachNoQuaHan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DanhSachNoQuaHan");
        }
    
        public virtual int sp_MuonSach(string maPhieu, string maDG, string maNV, string maBS, Nullable<int> soNgayMuon)
        {
            var maPhieuParameter = maPhieu != null ?
                new ObjectParameter("MaPhieu", maPhieu) :
                new ObjectParameter("MaPhieu", typeof(string));
    
            var maDGParameter = maDG != null ?
                new ObjectParameter("MaDG", maDG) :
                new ObjectParameter("MaDG", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maBSParameter = maBS != null ?
                new ObjectParameter("MaBS", maBS) :
                new ObjectParameter("MaBS", typeof(string));
    
            var soNgayMuonParameter = soNgayMuon.HasValue ?
                new ObjectParameter("SoNgayMuon", soNgayMuon) :
                new ObjectParameter("SoNgayMuon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MuonSach", maPhieuParameter, maDGParameter, maNVParameter, maBSParameter, soNgayMuonParameter);
        }
    
        public virtual int sp_TraSach(string maPhieu, string maBS, Nullable<System.DateTime> ngayTra)
        {
            var maPhieuParameter = maPhieu != null ?
                new ObjectParameter("MaPhieu", maPhieu) :
                new ObjectParameter("MaPhieu", typeof(string));
    
            var maBSParameter = maBS != null ?
                new ObjectParameter("MaBS", maBS) :
                new ObjectParameter("MaBS", typeof(string));
    
            var ngayTraParameter = ngayTra.HasValue ?
                new ObjectParameter("NgayTra", ngayTra) :
                new ObjectParameter("NgayTra", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TraSach", maPhieuParameter, maBSParameter, ngayTraParameter);
        }
    }
}
