//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ThongKeSach
    {
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public string CacTheLoai { get; set; }
        public Nullable<int> SoLuongSanSang { get; set; }
    }
}
